api/urls.py
from django.urls import path

from api import views

app_name = "api"


urlpatterns = [
    path('v1/list/grantgoal/', views.ListGrantGoalAPIView.as_view(), name="list_gg_api"),
    path('v1/create/grantgoal/', views.CreateGrantGoalAPIView.as_view(), name="create_gg_api"),
    path('v1/detail/grantgoal/<int:pk>/', views.DetailGrantGoalAPIView.as_view(), name="detail_gg_api"),
    path('v1/update/grantgoal/<int:pk>/', views.UpdateGrantGoalAPIView.as_view(), name="update_gg_api"),
    path('v1/delete/grantgoal/<int:pk>/', views.DeleteGrantGoalAPIView.as_view(), name="delete_gg_api"),
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"


urlpatterns = [
    ##### GRANTGOAL URLS #####
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="list_gg"),
    path('new/grantgoal/', views.NewGrantGoal.as_view(), name="create_gg"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_gg"),
    path('update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_gg"),
    path('delete/grantgoal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="delete_gg"),

    ##### SUBGRANTGOAL URLS #####
    path('list/subgrantgoal/', views.ListSubGrantGoal.as_view(), name="list_sgg"),
    path('new/subgrantgoal/', views.NewSubGrantGoal.as_view(), name="create_sgg"),
    path('detail/subgrantgoal/<int:pk>/', views.DetailSubGrantGoal.as_view(), name="detail_sgg"),
    path('update/subgrantgoal/<int:pk>/', views.UpdateSubGrantGoal.as_view(), name="update_sgg"),
    path('delete/subgrantgoal/<int:pk>/', views.DeleteSubGrantGoal.as_view(), name="delete_sgg"),
]

home/urls.py
from django.urls import path

from home import views

app_name = "home"


urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('signup/', views.Signup.as_view(), name="signup"),

    ### URLS PROFILE ###
    path('list/profile/', views.ListProfile.as_view(), name="list_profile"),
    path('detail/profile/<int:pk>/', views.DetailProfile.as_view(), name="detail_profile"),
]

pem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
    path('api/', include("api.urls")),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=128, default="I Love Plesem System")
    avatar = models.ImageField(blank=True, null=True)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    updated = models.DateField(auto_now_add=False, auto_now=True)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=8)


    def __str__(self):
        return self.user.first_name
    
@receiver(post_save, sender=User)
def auto_profiling(sender, instance, **kwargs):
    if kwargs.get('created', False):
        Profile.objects.get_or_create(user=instance)

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.Form):
    username = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"form-control"}))
    password = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control"}))



class SignupForm(UserCreationForm):
    username = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Username"})) 
    password1 = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Escribe tu Password"}))
    password2 = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Confirma tu Password"}))  
    first_name = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu First Name"})) 
    last_name = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Last Name"})) 
    email = forms.EmailField(max_length=32, widget=forms.EmailInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Email"})) 

home/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.urls import reverse_lazy

from core.models import GrantGoal
from .models import Profile
from .forms import LoginForm, SignupForm

# Create your views here.

class Index(generic.View):
    template_name = "home/index.html"
    context = {}
    form_class = LoginForm

    def get(self, request):
        self.context = {
            "grantgoals": GrantGoal.objects.filter(status=True),
            "form": self.form_class
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("home:index")
        return redirect("home:index")



class Logout(generic.View):
    def get(self, request):
        logout(request)
        return redirect("home:index")
    


class Signup(generic.CreateView):
    template_name = "home/signup.html"
    model = User
    form_class = SignupForm
    success_url = reverse_lazy("home:index")

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
            return redirect("home:index")
        return redirect("home:index")
    


class ListProfile(generic.View):
    template_name = "home/list_profile.html"
    context = {}

    def get(self, request):
        self.context = {
            "profiles": Profile.objects.filter(status=True)
        }
        return render(request, self.template_name, self.context)
    


class DetailProfile(generic.View):
    template_name = "home/detail_profile.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "profile": Profile.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)

templates/home/detail_profile.html
{% extends "base/base.html" %}

{% block title %}DETAIL PROFILE VIEW{% endblock title %}

{% block content %}
    <h3>{{ profile.user.first_name }}</h3>
    <h3>{{ profile.user.last_name }}</h3>
    <h3>{{ profile.bio }}</h3>

    <a href="{% url 'home:list_profile' %}">Return</a>
{% endblock content %}

templates/home/index.html
{% extends "base/base.html" %}

{% block title %}INDEX VIEW{% endblock title %}

{% block content %}

{% if request.user.is_authenticated %}
    <h3>Bienvenido a PleSem System user: "{{ request.user }}"</h3>
<table class="table table-striped">
    <thead>
        <th>ID</th>
        <th>NAME</th>
        <th>USER</th>
        <th>TIMESTAMP</th>
        <th></th>
        <th>ACTIONS</th>
        <th></th>
    </thead>
    <tbody>
        {% for gg in grantgoals %}
            <tr>
                <td>{{ gg.id }}</td>
                <td>{{ gg.ggname }}</td>
                <td>{{ gg.user }}</td>
                <td>{{ gg.timestamp }}</td>
                <td><a href="{% url 'core:detail_gg' gg.pk %}" class="btn btn-outline-info">Detail</a></td>
                <td><a href="" class="btn btn-outline-warning">Update</a></td>
                <td><a href="" class="btn btn-outline-danger">Delete</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<hr>
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary form-control">LogIn</button>
            <a href="{% url 'home:index' %}" class="btn btn-warning form-control">Cancel</a>
    </form>
    <hr>
    Si no tienes una cuenta,<a href="{% url  'home:signup' %}">registrate aqui!</a>
{% endif %}
{% endblock content %}

templates/home/list_profile.html
{% extends "base/base.html" %}

{% block title %}LIST PROFILE VIEW{% endblock title %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>NAME</th>
            <th>TIMESTAMP</th>
            <th>STATUS</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            
            {% for profile in  profiles %}
                <tr>
                    <td>{{ profile.id }}</td>
                    <td>{{ profile.user.first_name }}</td>
                    <td>{{ profile.timestamp }}</td>
                    <td>{{ profile.status }}</td>
                    <td><a href="{% url 'home:detail_profile' profile.id %}" class="btn btn-outline-info sm">Detail</a></td>
                    <td><a href="" class="btn btn-outline-warning sm">Update</a></td>
                    <td><a href="" class="btn btn-outline-danger sm">Delete</a></td>
                </tr>        
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/home/signup.html
{% extends "base/base.html" %}


{% block title %}NEW USER VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-success form-control">Signup</button>
            <a href="{% url 'home:index' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}