api/urls.py
from django.urls import path

from api import views

app_name = "api"


urlpatterns = [
    path('v1/list/grantgoal/', views.ListGrantGoalAPIView.as_view(), name="list_gg_api"),
    path('v1/create/grantgoal/', views.CreateGrantGoalAPIView.as_view(), name="create_gg_api"),
    path('v1/detail/grantgoal/<int:pk>/', views.DetailGrantGoalAPIView.as_view(), name="detail_gg_api"),
    path('v1/update/grantgoal/<int:pk>/', views.UpdateGrantGoalAPIView.as_view(), name="update_gg_api"),
    path('v1/delete/grantgoal/<int:pk>/', views.DeleteGrantGoalAPIView.as_view(), name="delete_gg_api"),
]

home/urls.py
from django.urls import path

from home import views

app_name = "home"


urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('signup/', views.Signup.as_view(), name="signup"),

    ### URLS PROFILE ###
    path('list/profile/', views.ListProfile.as_view(), name="list_profile"),
    path('detail/profile/<int:pk>/', views.DetailProfile.as_view(), name="detail_profile"),
]

pem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
    path('api/', include("api.urls")),
]

templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
  </head>
  <body>
    
    <div class="row">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:index' %}">Link</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="">Another action</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                  </li>
                </ul>
                <li class="nav-item">
                  <a class="nav-link" aria-disabled="false" href="{% url 'home:logout' %}">Logout</a>
                </li>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                
              </div>
            </div>
          </nav>
    </div>
    <hr>
    <div class="row">
        <div class="col-2">

        </div>
        <div class="col-8">
            {% block content %}
            {% endblock content %}
        </div>
        <div class="col-2">

        </div>
    </div>
    <hr>
    <div class="row">

    </div>

    <script src="{% static 'js/bootstrap.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
  </body>
</html>