api/urls.py
from django.urls import path

from api import views

app_name = "api"


urlpatterns = [
    path('v1/list/grantgoal/', views.ListGrantGoalAPIView.as_view(), name="list_gg_api"),
    path('v1/create/grantgoal/', views.CreateGrantGoalAPIView.as_view(), name="create_gg_api"),
    path('v1/detail/grantgoal/<int:pk>/', views.DetailGrantGoalAPIView.as_view(), name="detail_gg_api"),
    path('v1/update/grantgoal/<int:pk>/', views.UpdateGrantGoalAPIView.as_view(), name="update_gg_api"),
    path('v1/delete/grantgoal/<int:pk>/', views.DeleteGrantGoalAPIView.as_view(), name="delete_gg_api"),
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"


urlpatterns = [
    ##### GRANTGOAL URLS #####
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="list_gg"),
    path('new/grantgoal/', views.NewGrantGoal.as_view(), name="create_gg"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_gg"),
    path('update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_gg"),
    path('delete/grantgoal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="delete_gg"),

    ##### SUBGRANTGOAL URLS #####
    path('list/subgrantgoal/', views.ListSubGrantGoal.as_view(), name="list_sgg"),
    path('new/subgrantgoal/', views.NewSubGrantGoal.as_view(), name="create_sgg"),
    path('detail/subgrantgoal/<int:pk>/', views.DetailSubGrantGoal.as_view(), name="detail_sgg"),
    path('update/subgrantgoal/<int:pk>/', views.UpdateSubGrantGoal.as_view(), name="update_sgg"),
    path('delete/subgrantgoal/<int:pk>/', views.DeleteSubGrantGoal.as_view(), name="delete_sgg"),
]

pem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
    path('api/', include("api.urls")),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta
from django.urls import reverse

# Create your models here.



CHOICES_LEVEL = (
    ("HEIGHT", "HG"),
    ("MIDDLE", "MD"),
    ("LOW", "LW"),
)

CHIOCES_STATE = (
    ("NOT STARTED", "NS"),
    ("DOING", "DG"),
    ("DONE", "DN"),
)

class GrantGoal(models.Model):
    ggname = models.CharField(max_length=64, default="Generic Grant Goal")
    description = models.CharField(max_length=128, default="Generic Grant Goal description")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    progress = models.FloatField(default=0.0)
    priority = models.CharField(max_length=8, choices=CHOICES_LEVEL)
    state = models.CharField(max_length=16, choices=CHIOCES_STATE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=8)

    def __str__(self):
        return self.ggname
    
    def get_absolute_url(self):
        return reverse("detail_gg", kwargs={"pk": self.pk})
    
@receiver(post_save, sender=GrantGoal)
def auto_final_date_GG(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()




class Area(models.Model):
    area_name = models.CharField(max_length=32, default="Generic Area")
    description = models.CharField(max_length=128, default="Generic Activities")

    def __str__(self):
        return self.area_name




CHOICES_LEVEL_SUB = (
    ("HEIGHT", "HG"),
    ("MIDDLE", "MD"),
    ("LOW", "LW"),
)

CHIOCES_STATE_SUB = (
    ("NOT STARTED", "NS"),
    ("DOING", "DG"),
    ("DONE", "DN"),
)

class SubGrantGoal(models.Model):
    sggname = models.CharField(max_length=64, default="Generic Sub Grant Goal")
    description = models.CharField(max_length=128, default="Generic Sub Grant Goal description")
    grantgoal = models.ForeignKey(GrantGoal, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    progress = models.FloatField(default=0.0)
    priority = models.CharField(max_length=8, choices=CHOICES_LEVEL_SUB)
    state = models.CharField(max_length=16, choices=CHIOCES_STATE_SUB)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=8)

    def __str__(self):
        return self.sggname


@receiver(post_save, sender=SubGrantGoal)
def auto_final_date_SGG(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()






CHOICES_LEVEL_GOAL = (
    ("HEIGHT", "HG"),
    ("MIDDLE", "MD"),
    ("LOW", "LW"),
)

CHIOCES_STATE_GOAL = (
    ("NOT STARTED", "NS"),
    ("DOING", "DG"),
    ("DONE", "DN"),
)

class Goal(models.Model):
    goalname = models.CharField(max_length=64, default="Generic Goal")
    description = models.CharField(max_length=128, default="Generic Goal description")
    subgrantgoal = models.ForeignKey(SubGrantGoal, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    progress = models.FloatField(default=0.0)
    priority = models.CharField(max_length=8, choices=CHOICES_LEVEL_GOAL)
    state = models.CharField(max_length=16, choices=CHIOCES_STATE_GOAL)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=8)

    def __str__(self):
        return self.goalname


@receiver(post_save, sender=Goal)
def auto_final_date_G(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()





CHOICES_LEVEL_ISSUE = (
    ("HEIGHT", "HG"),
    ("MIDDLE", "MD"),
    ("LOW", "LW"),
)

CHIOCES_STATE_ISSUE = (
    ("NOT STARTED", "NS"),
    ("DOING", "DG"),
    ("DONE", "DN"),
)

class Issue(models.Model):
    issuename = models.CharField(max_length=64, default="Generic Issue")
    description = models.CharField(max_length=128, default="Generic Issue description")
    goal = models.ForeignKey(Goal, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    progress = models.FloatField(default=0.0)
    priority = models.CharField(max_length=8, choices=CHOICES_LEVEL_ISSUE)
    state = models.CharField(max_length=16, choices=CHIOCES_STATE_ISSUE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=8)

    def __str__(self):
        return self.issuename



@receiver(post_save, sender=Issue)
def auto_final_date_I(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()

core/forms.py
from django import forms

from .models import GrantGoal, SubGrantGoal


class NewGrantGoalForm(forms.ModelForm):
    class Meta:
        model = GrantGoal
        fields = [
            "ggname",
            "description",
            "user",
            "days_duration",
            "state",
            "status",
            "slug"
        ]
        widgets = {
            "ggname": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el GrantGoal Name"}),
            "description": forms.Textarea(attrs={"rows": 3, "type":"text", "class":"form-control", "placeholder":"Escribe el GrantGoal Description"}),
            "user": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el GrantGoal Slug"}),
        }



class UpdateGrantGoalForm(forms.ModelForm):
    class Meta:
        model = GrantGoal
        fields = [
            "ggname",
            "description",
            "user",
            "days_duration",
            "state",
            "status",
            "slug"
        ]
        widgets = {
            "ggname": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el GrantGoal Name"}),
            "description": forms.Textarea(attrs={"rows": 3, "type":"text", "class":"form-control", "placeholder":"Escribe el GrantGoal Description"}),
            "user": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el GrantGoal Slug"}),
        }

    

class NewSubGrantGoalForm(forms.ModelForm):
    class Meta:
        model = SubGrantGoal
        fields = [
            "sggname",
            "description",
            "user",
            "grantgoal",
            "area",
            "days_duration",
            "state",
            "status",
            "slug"
        ]
        widgets = {
            "sggname": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el GrantGoal Name"}),
            "description": forms.Textarea(attrs={"rows": 3, "type":"text", "class":"form-control", "placeholder":"Escribe el GrantGoal Description"}),
            "user": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "grantgoal": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "area": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el GrantGoal Slug"}),
        }



class UpdateSubGrantGoalForm(forms.ModelForm):
    class Meta:
        model = SubGrantGoal
        fields = [
            "sggname",
            "description",
            "user",
            "grantgoal",
            "area",
            "days_duration",
            "state",
            "status",
            "slug"
        ]
        widgets = {
            "sggname": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el GrantGoal Name"}),
            "description": forms.Textarea(attrs={"rows": 3, "type":"text", "class":"form-control", "placeholder":"Escribe el GrantGoal Description"}),
            "user": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "grantgoal": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "area": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "state": forms.Select(attrs={"type":"select", "class":"form-control"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox"}),
            "slug": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el GrantGoal Slug"}),
        }

core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from core import models
from core import forms 

# Create your views here.

# # # #  C R U D G R A N T G O A L  # # # # #

### CREATE
class NewGrantGoal(generic.CreateView):
    template_name = "core/create_gg.html"
    model = models.GrantGoal
    form_class = forms.NewGrantGoalForm
    success_url = reverse_lazy("core:list_gg")

### RETRIEVE
## List
class ListGrantGoal(generic.View):
    template_name = "core/list_gg.html"
    context = {}

    def get(self, request):
        self.context = {
            "grantgoals": models.GrantGoal.objects.filter(status=True)
        }
        return render(request, self.template_name, self.context)
    
## Detail
class DetailGrantGoal(generic.View):
    template_name = "core/detail_gg.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "grantgoal": models.GrantGoal.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)

### UPDATE
class UpdateGrantGoal(generic.UpdateView):
    template_name = "core/update_gg.html"
    model = models.GrantGoal
    form_class = forms.UpdateGrantGoalForm
    success_url = reverse_lazy("core:list_gg")


### DELETE
class DeleteGrantGoal(generic.DeleteView):
    template_name = "core/delete_gg.html"
    model = models.GrantGoal
    success_url = reverse_lazy("core:list_gg")



# # # #  C R U D   S U B G R A N T G O A L  # # # # #

### CREATE
class NewSubGrantGoal(generic.CreateView):
    template_name = "core/create_sgg.html"
    model = models.SubGrantGoal
    form_class = forms.NewSubGrantGoalForm
    success_url = reverse_lazy("core:list_sgg")

### RETRIEVE
## List
class ListSubGrantGoal(generic.ListView):
    template_name = "core/list_sgg.html"
    queryset = models.SubGrantGoal.objects.filter(status=True)

## Detail
class DetailSubGrantGoal(generic.DetailView):
    template_name = "core/detail_sgg.html"
    model = models.SubGrantGoal


### UPDATE
class UpdateSubGrantGoal(generic.UpdateView):
    template_name = "core/update_sgg.html"
    model = models.SubGrantGoal
    form_class = forms.UpdateSubGrantGoalForm
    success_url = reverse_lazy("core:list_sgg")


### DELETE
class DeleteSubGrantGoal(generic.DeleteView):
    template_name = "core/delete_sgg.html"
    model = models.SubGrantGoal
    success_url = reverse_lazy("core:list_sgg")



# # # #  C R U D    G O A L  # # # # #

### CREATE

### RETRIEVE
## List

## Detail

### UPDATE


# # # #  C R U D   ISSUES  # # # # #

### CREATE

### RETRIEVE
## List

## Detail

### UPDATE


# # # #  C R U D   AREA  # # # # #

### CREATE

### RETRIEVE
## List

## Detail

### UPDATE

templates/core/create_gg.html
{% extends "base/base.html" %}

{% block title %}NEW GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button style="margin: 2%;" type="submit" class="btn btn-outline-success form-control">New Grant Goal</button>
            <br>
            <a href="{% url 'core:list_gg' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/create_sgg.html
{% extends "base/base.html" %}

{% block title %}NEW SUBGRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button style="margin: 2%;" type="submit" class="btn btn-outline-success form-control">New SubGrant Goal</button>
            <br>
            <a href="{% url 'core:list_sgg' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/delete_gg.html
{% extends "base/base.html" %}

{% block title %}DELETE GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h3>¿Realmente deseas eliminar el GrantGoal: "{{ object }}"?</h3>
            
            <button type="submit" class="btn btn-outline-danger">Delete GrantGoal</button>
            <a href="{% url 'core:list_gg' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/delete_sgg.html
{% extends "base/base.html" %}

{% block title %}DELETE SUBGRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h3>¿Realmente deseas eliminar el SubGrantGoal: "{{ object }}"?</h3>
            
            <button type="submit" class="btn btn-outline-danger">Delete SubGrantGoal</button>
            <a href="{% url 'core:list_sgg' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/detail_gg.html
{% extends "base/base.html" %}

{% block title %}DETAIL GRANT GOAL VIEW{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          General Data
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          This is the grantgoal name: <strong>{{ grantgoal.ggname }}</strong> It is the description: {{ grantgoal.description }}, and its progress is: <code>{{ grantgoal.progress }} %</code>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          This is the grantgoal timestamp.<strong>{{ grantgoal.timestamp }}</strong> It is the days duration to the grantgoal: {{ grantgoal.days_duration }}, and its final data is: <code>{{ grantgoal.final_date }}</code>.
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Status Data
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          This is the grantgoal state: <strong>{{ grantgoal.state }}</strong> and  It is the grantgoal status: {{ grantgoal.status }} and it is the grantgoal priority:  <code>{{ grantgoal.priority }}</code>.
        </div>
      </div>
    </div>
  </div>
  <a href="{% url 'core:list_gg' %}">Return</a>
{% endblock content %}

templates/core/detail_sgg.html
{% extends "base/base.html" %}

{% block title %}DETAIL SUBGRANT GOAL VIEW{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          General Data
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          This is the grantgoal name: <strong>{{ object.sggname }}</strong> It is the description: {{ object.description }}, and its progress is: <code>{{ object.progress }} %</code>
          Related grantgoal: <code>{{ object.grantgoal }} </code>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          This is the grantgoal timestamp.<strong>{{ object.timestamp }}</strong> It is the days duration to the grantgoal: {{ object.days_duration }}, and its final data is: <code>{{ object.final_date }}</code>.
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Status Data
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          This is the grantgoal state: <strong>{{ object.state }}</strong> and  It is the grantgoal status: {{ object.status }} and it is the grantgoal priority:  <code>{{ object.priority }}</code>.
        </div>
      </div>
    </div>
  </div>
  <a href="{% url 'core:list_sgg' %}">Return</a>
{% endblock content %}

templates/core/list_gg.html
{% extends "base/base.html" %}

{% block title %}LIST GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <a href="{% url 'core:create_gg' %}" class="btn btn-outline-success form-control">New Grant Goal</a>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>NAME</th>
            <th>USER</th>
            <th>TIMESTAMP</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for gg in grantgoals %}
                <tr>
                    <td>{{ gg.id }}</td>
                    <td>{{ gg.ggname }}</td>
                    <td>{{ gg.user }}</td>
                    <td>{{ gg.timestamp }}</td>
                    <td><a href="{% url 'core:detail_gg' gg.pk %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'core:update_gg' gg.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_gg' gg.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}
    

templates/core/list_sgg.html
{% extends "base/base.html" %}

{% block title %}LIST SUB GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <a href="{% url 'core:create_sgg' %}" class="btn btn-outline-success form-control">New Grant Goal</a>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>NAME</th>
            <th>GRANTGOAL</th>
            <th>USER</th>
            <th>TIMESTAMP</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for sgg in object_list %}
                <tr>
                    <td>{{ sgg.id }}</td>
                    <td>{{ sgg.sggname }}</td>
                    <td>{{ sgg.grantgoal }}</td>
                    <td>{{ sgg.user }}</td>
                    <td>{{ sgg.timestamp }}</td>
                    <td><a href="{% url 'core:detail_sgg' sgg.pk %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'core:update_sgg' sgg.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_sgg' sgg.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}
    

templates/core/update_gg.html
{% extends "base/base.html" %}

{% block title %}UPDATE GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button style="margin: 2%;" type="submit" class="btn btn-outline-primary form-control">Update Grant Goal</button>
            <br>
            <a href="{% url 'core:list_gg' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/update_sgg.html
{% extends "base/base.html" %}

{% block title %}UPDATE SUBGRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button style="margin: 2%;" type="submit" class="btn btn-outline-primary form-control">Update Sub Grant Goal</button>
            <br>
            <a href="{% url 'core:list_sgg' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}